/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesteOnboardingRouteImport } from './routes/teste-onboarding'
import { Route as ResumoRouteImport } from './routes/resumo'
import { Route as Protocolo21DiasRouteImport } from './routes/protocolo-21-dias'
import { Route as PrimeirosPassosRouteImport } from './routes/primeiros-passos'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as OpcoesMetodoRouteImport } from './routes/opcoes-metodo'
import { Route as MinhaOrquideaRouteImport } from './routes/minha-orquidea'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InicioDemoRouteImport } from './routes/inicio-demo'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as BemVindoRouteImport } from './routes/bem-vindo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AprenderRouteImport } from './routes/aprender'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TesteOnboardingRoute = TesteOnboardingRouteImport.update({
  id: '/teste-onboarding',
  path: '/teste-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumoRoute = ResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => rootRouteImport,
} as any)
const Protocolo21DiasRoute = Protocolo21DiasRouteImport.update({
  id: '/protocolo-21-dias',
  path: '/protocolo-21-dias',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeirosPassosRoute = PrimeirosPassosRouteImport.update({
  id: '/primeiros-passos',
  path: '/primeiros-passos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const OpcoesMetodoRoute = OpcoesMetodoRouteImport.update({
  id: '/opcoes-metodo',
  path: '/opcoes-metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaOrquideaRoute = MinhaOrquideaRouteImport.update({
  id: '/minha-orquidea',
  path: '/minha-orquidea',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioDemoRoute = InicioDemoRouteImport.update({
  id: '/inicio-demo',
  path: '/inicio-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const BemVindoRoute = BemVindoRouteImport.update({
  id: '/bem-vindo',
  path: '/bem-vindo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AprenderRoute = AprenderRouteImport.update({
  id: '/aprender',
  path: '/aprender',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof BemVindoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/inicio': typeof InicioRoute
  '/inicio-demo': typeof InicioDemoRoute
  '/mcp': typeof McpRoute
  '/metodo': typeof MetodoRoute
  '/minha-orquidea': typeof MinhaOrquideaRoute
  '/opcoes-metodo': typeof OpcoesMetodoRoute
  '/plano': typeof PlanoRoute
  '/primeiros-passos': typeof PrimeirosPassosRoute
  '/protocolo-21-dias': typeof Protocolo21DiasRoute
  '/resumo': typeof ResumoRoute
  '/teste-onboarding': typeof TesteOnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof BemVindoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/inicio': typeof InicioRoute
  '/inicio-demo': typeof InicioDemoRoute
  '/mcp': typeof McpRoute
  '/metodo': typeof MetodoRoute
  '/minha-orquidea': typeof MinhaOrquideaRoute
  '/opcoes-metodo': typeof OpcoesMetodoRoute
  '/plano': typeof PlanoRoute
  '/primeiros-passos': typeof PrimeirosPassosRoute
  '/protocolo-21-dias': typeof Protocolo21DiasRoute
  '/resumo': typeof ResumoRoute
  '/teste-onboarding': typeof TesteOnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprender': typeof AprenderRoute
  '/auth': typeof AuthRoute
  '/bem-vindo': typeof BemVindoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/diario': typeof DiarioRoute
  '/inicio': typeof InicioRoute
  '/inicio-demo': typeof InicioDemoRoute
  '/mcp': typeof McpRoute
  '/metodo': typeof MetodoRoute
  '/minha-orquidea': typeof MinhaOrquideaRoute
  '/opcoes-metodo': typeof OpcoesMetodoRoute
  '/plano': typeof PlanoRoute
  '/primeiros-passos': typeof PrimeirosPassosRoute
  '/protocolo-21-dias': typeof Protocolo21DiasRoute
  '/resumo': typeof ResumoRoute
  '/teste-onboarding': typeof TesteOnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprender'
    | '/auth'
    | '/bem-vindo'
    | '/diagnostico'
    | '/diario'
    | '/inicio'
    | '/inicio-demo'
    | '/mcp'
    | '/metodo'
    | '/minha-orquidea'
    | '/opcoes-metodo'
    | '/plano'
    | '/primeiros-passos'
    | '/protocolo-21-dias'
    | '/resumo'
    | '/teste-onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprender'
    | '/auth'
    | '/bem-vindo'
    | '/diagnostico'
    | '/diario'
    | '/inicio'
    | '/inicio-demo'
    | '/mcp'
    | '/metodo'
    | '/minha-orquidea'
    | '/opcoes-metodo'
    | '/plano'
    | '/primeiros-passos'
    | '/protocolo-21-dias'
    | '/resumo'
    | '/teste-onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/aprender'
    | '/auth'
    | '/bem-vindo'
    | '/diagnostico'
    | '/diario'
    | '/inicio'
    | '/inicio-demo'
    | '/mcp'
    | '/metodo'
    | '/minha-orquidea'
    | '/opcoes-metodo'
    | '/plano'
    | '/primeiros-passos'
    | '/protocolo-21-dias'
    | '/resumo'
    | '/teste-onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprenderRoute: typeof AprenderRoute
  AuthRoute: typeof AuthRoute
  BemVindoRoute: typeof BemVindoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  DiarioRoute: typeof DiarioRoute
  InicioRoute: typeof InicioRoute
  InicioDemoRoute: typeof InicioDemoRoute
  McpRoute: typeof McpRoute
  MetodoRoute: typeof MetodoRoute
  MinhaOrquideaRoute: typeof MinhaOrquideaRoute
  OpcoesMetodoRoute: typeof OpcoesMetodoRoute
  PlanoRoute: typeof PlanoRoute
  PrimeirosPassosRoute: typeof PrimeirosPassosRoute
  Protocolo21DiasRoute: typeof Protocolo21DiasRoute
  ResumoRoute: typeof ResumoRoute
  TesteOnboardingRoute: typeof TesteOnboardingRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teste-onboarding': {
      id: '/teste-onboarding'
      path: '/teste-onboarding'
      fullPath: '/teste-onboarding'
      preLoaderRoute: typeof TesteOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumo': {
      id: '/resumo'
      path: '/resumo'
      fullPath: '/resumo'
      preLoaderRoute: typeof ResumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo-21-dias': {
      id: '/protocolo-21-dias'
      path: '/protocolo-21-dias'
      fullPath: '/protocolo-21-dias'
      preLoaderRoute: typeof Protocolo21DiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primeiros-passos': {
      id: '/primeiros-passos'
      path: '/primeiros-passos'
      fullPath: '/primeiros-passos'
      preLoaderRoute: typeof PrimeirosPassosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opcoes-metodo': {
      id: '/opcoes-metodo'
      path: '/opcoes-metodo'
      fullPath: '/opcoes-metodo'
      preLoaderRoute: typeof OpcoesMetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-orquidea': {
      id: '/minha-orquidea'
      path: '/minha-orquidea'
      fullPath: '/minha-orquidea'
      preLoaderRoute: typeof MinhaOrquideaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio-demo': {
      id: '/inicio-demo'
      path: '/inicio-demo'
      fullPath: '/inicio-demo'
      preLoaderRoute: typeof InicioDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bem-vindo': {
      id: '/bem-vindo'
      path: '/bem-vindo'
      fullPath: '/bem-vindo'
      preLoaderRoute: typeof BemVindoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprender': {
      id: '/aprender'
      path: '/aprender'
      fullPath: '/aprender'
      preLoaderRoute: typeof AprenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprenderRoute: AprenderRoute,
  AuthRoute: AuthRoute,
  BemVindoRoute: BemVindoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  DiarioRoute: DiarioRoute,
  InicioRoute: InicioRoute,
  InicioDemoRoute: InicioDemoRoute,
  McpRoute: McpRoute,
  MetodoRoute: MetodoRoute,
  MinhaOrquideaRoute: MinhaOrquideaRoute,
  OpcoesMetodoRoute: OpcoesMetodoRoute,
  PlanoRoute: PlanoRoute,
  PrimeirosPassosRoute: PrimeirosPassosRoute,
  Protocolo21DiasRoute: Protocolo21DiasRoute,
  ResumoRoute: ResumoRoute,
  TesteOnboardingRoute: TesteOnboardingRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
